export const COMPLAINT_TOPICS = [
    { id: 1, label: "Billing Issue - Other", priority: "medium" },
    { id: 2, label: "Billing Issue - Weight Discrepancy", priority: "high" },
    { id: 3, label: "Change COD Amount", priority: "medium" },
    { id: 4, label: "Close the Account", priority: "low" },
    {
        id: 5,
        label: "COD - Parcel Delivered but not marked as Delivered by courier",
        priority: "high",
    },
    { id: 6, label: "COD - Remittance not received", priority: "high" },
    { id: 7, label: "Convert COD to Prepaid", priority: "medium" },
    { id: 8, label: "Convert Prepaid to COD", priority: "medium" },
    { id: 9, label: "Damage in Transit", priority: "high" },
    { id: 10, label: "DC Address Request", priority: "low" },
    { id: 11, label: "Delay in Delivery", priority: "high" },
    { id: 12, label: "Delay in Pickup", priority: "medium" },
    { id: 13, label: "Delay in Return", priority: "medium" },
    { id: 14, label: "Grievance", priority: "medium" },
    { id: 15, label: "Invoice", priority: "low" },
    { id: 16, label: "Other", priority: "low" },
    {
        id: 17,
        label: "Pickup Dispute - Parcel Picked but status is still Pending Pickup",
        priority: "high",
    },
    { id: 18, label: "Pincode Activation Delivery", priority: "medium" },
    { id: 19, label: "Pincode Activation - Pickup", priority: "medium" },
    { id: 20, label: "POD - Please provide Proof of Delivery", priority: "high" },
    { id: 21, label: "POD - Please provide Proof of Return", priority: "high" },
    {
        id: 22,
        label: "Product Mismatch - Incorrect Product Received",
        priority: "high",
    },
    { id: 23, label: "Re-Attempt Shipment Delivery", priority: "medium" },
    { id: 24, label: "Refund 30 days TAT Exceeded", priority: "medium" },
    { id: 25, label: "Refund - 45 days TAT Exceeded", priority: "medium" },
    { id: 26, label: "Refund - 60 days TAT Exceeded", priority: "high" },
    { id: 27, label: "Refund - Invalid POD", priority: "high" },
    { id: 28, label: "Refund - Lost Shipment", priority: "high" },
    { id: 29, label: "Refund Shipment Charges", priority: "medium" },
    { id: 30, label: "Shipment Creation Error", priority: "high" },
    { id: 31, label: "Shopify Tech Issue Suggestion", priority: "low" },
    { id: 32, label: "TDS Credit", priority: "medium" },
    { id: 33, label: "Technical", priority: "medium" },
    { id: 34, label: "Topup", priority: "medium" },
    {
        id: 35,
        label: "Untrackable in Ekart - Potentially Lost",
        priority: "high",
    },
    { id: 36, label: "Update Shipment - Change in Address", priority: "medium" },
    {
        id: 37,
        label: "Update Shipment - Change in Mobile number",
        priority: "medium",
    },
    {
        id: 38,
        label: "Update Shipment - Request RTO / Return",
        priority: "medium",
    },
    { id: 39, label: "Wallet Recharge / Topup Problem", priority: "high" },
    { id: 40, label: "Website Error", priority: "medium" },
    { id: 41, label: "Wordpress / Woocommerce Tech Issue", priority: "low" },
];
