export const STATES = [
  { name: "Andaman and Nicobar Islands", code: "AN", zone_id: 1475 },
  { name: "Andhra Pradesh", code: "AP", zone_id: 1476 },
  { name: "Arunachal Pradesh", code: "AR", zone_id: 1477 },
  { name: "Assam", code: "AS", zone_id: 1478 },
  { name: "Bihar", code: "BI", zone_id: 1479 },
  { name: "Chandigarh", code: "CH", zone_id: 1480 },
  { name: "Dadra and Nagar Haveli", code: "DA", zone_id: 1481 },
  { name: "Daman and Diu", code: "DM", zone_id: 1482 },
  { name: "Delhi", code: "DE", zone_id: 1483 },
  { name: "Goa", code: "GO", zone_id: 1484 },
  { name: "Gujarat", code: "GU", zone_id: 1485 },
  { name: "Haryana", code: "HA", zone_id: 1486 },
  { name: "Himachal Pradesh", code: "HP", zone_id: 1487 },
  { name: "Jammu and Kashmir", code: "JA", zone_id: 1488 },
  { name: "Karnataka", code: "KA", zone_id: 1489 },
  { name: "Kerala", code: "KE", zone_id: 1490 },
  { name: "Lakshadweep Islands", code: "LI", zone_id: 1491 },
  { name: "Madhya Pradesh", code: "MP", zone_id: 1492 },
  { name: "Maharashtra", code: "MA", zone_id: 1493 },
  { name: "Manipur", code: "MN", zone_id: 1494 },
  { name: "Meghalaya", code: "ME", zone_id: 1495 },
  { name: "Mizoram", code: "MI", zone_id: 1496 },
  { name: "Nagaland", code: "NA", zone_id: 1497 },
  { name: "Odisha", code: "OD", zone_id: 1498 },
  { name: "Puducherry", code: "PO", zone_id: 1499 },
  { name: "Punjab", code: "PU", zone_id: 1500 },
  { name: "Rajasthan", code: "RA", zone_id: 1501 },
  { name: "Sikkim", code: "SI", zone_id: 1502 },
  { name: "Tamil Nadu", code: "TN", zone_id: 1503 },
  { name: "Tripura", code: "TR", zone_id: 1504 },
  { name: "Uttar Pradesh", code: "UP", zone_id: 1505 },
  { name: "West Bengal", code: "WB", zone_id: 1506 },
  { name: "Telangana", code: "TS", zone_id: 4231 },
  { name: "Jharkhand", code: "JH", zone_id: 4239 },
  { name: "Uttarakhand", code: "UK", zone_id: 4240 },
  { name: "Chattisgarh", code: "CG", zone_id: 4241 },
  { name: "Ladakh", code: "LA", zone_id: 4242 },
];

export const COUNTRIES = [
  { name: "Afghanistan", code: "AF" },
  { name: "Albania", code: "AL" },
  { name: "Algeria", code: "DZ" },
  { name: "Andorra", code: "AD" },
  { name: "Angola", code: "AO" },
  { name: "Argentina", code: "AR" },
  { name: "Armenia", code: "AM" },
  { name: "Australia", code: "AU" },
  { name: "Austria", code: "AT" },
  { name: "Bangladesh", code: "BD" },
  { name: "Belgium", code: "BE" },
  { name: "Bhutan", code: "BT" },
  { name: "Brazil", code: "BR" },
  { name: "Canada", code: "CA" },
  { name: "China", code: "CN" },
  { name: "Denmark", code: "DK" },
  { name: "Egypt", code: "EG" },
  { name: "Finland", code: "FI" },
  { name: "France", code: "FR" },
  { name: "Germany", code: "DE" },
  { name: "Greece", code: "GR" },
  { name: "India", code: "IN" },
  { name: "Indonesia", code: "ID" },
  { name: "Iran", code: "IR" },
  { name: "Iraq", code: "IQ" },
  { name: "Ireland", code: "IE" },
  { name: "Italy", code: "IT" },
  { name: "Japan", code: "JP" },
  { name: "Malaysia", code: "MY" },
  { name: "Mexico", code: "MX" },
  { name: "Nepal", code: "NP" },
  { name: "Netherlands", code: "NL" },
  { name: "New Zealand", code: "NZ" },
  { name: "Nigeria", code: "NG" },
  { name: "Norway", code: "NO" },
  { name: "Pakistan", code: "PK" },
  { name: "Philippines", code: "PH" },
  { name: "Poland", code: "PL" },
  { name: "Portugal", code: "PT" },
  { name: "Qatar", code: "QA" },
  { name: "Russia", code: "RU" },
  { name: "Saudi Arabia", code: "SA" },
  { name: "Singapore", code: "SG" },
  { name: "South Africa", code: "ZA" },
  { name: "South Korea", code: "KR" },
  { name: "Spain", code: "ES" },
  { name: "Sri Lanka", code: "LK" },
  { name: "Sweden", code: "SE" },
  { name: "Switzerland", code: "CH" },
  { name: "Thailand", code: "TH" },
  { name: "Turkey", code: "TR" },
  { name: "Ukraine", code: "UA" },
  { name: "United Arab Emirates", code: "AE" },
  { name: "United Kingdom", code: "GB" },
  { name: "United States", code: "US" },
  { name: "Vietnam", code: "VN" },
];

// NDR Event Type descriptions
export const NDR_EVENT_DESCRIPTIONS = {
  "REATTEMPT-CONTACT": "Consignee address incomplete/wrong or not reachable",
  REATTEMPT: "Delivery attempt failed",
  MISROUTE: "Shipment is in wrong delivery pincode",
  "DC-ADDRESS": "Delivery address is ODA - self collection required",
  "URGENT-DELIVERY": "Delivery detected as beyond EDD",
  "REATTEMPT-COD-NOT-READY": "Consignee did not have COD amount ready",
  "RTO-MISSING": "Shipment is missing while in return",
  "OPEN-DELIVERY": "Consignee asked for open delivery",
  "CONSIGNEE-OPENED": "Consignee opened parcel and refused delivery",
  REFUSED: "Consignee refused to accept shipment",
  "RTO-REATTEMPT": "Return shipment delivery attempt failed",
  "REATTEMPT-NEW-DATE": "Consignee asked for future delivery date",
  "REATTEMPT-RESTRICTED": "Address entry restricted",
  ENTRY: "Entry restriction issue",
  "RTO-PACKING": "Return shipment packing issue",
  "REATTEMPT-CUST-REFUSED": "Customer refused shipment",
  "REATTEMPT-OTP": "Consignee did not have OTP",
  "MANUAL-VERIFY": "Manual verification needed",
  "RTO-SECURITY": "Returned due to security reasons",
  "FINANCE-EMBARGO": "Held due to payment issue",
  "EWAY-SEND": "Pending E-Way bill information",
  "REATTEMPT-DAMAGE": "Shipment is damaged",
  "REATTEMPT-RTO-REFUSED": "Return shipment refused by shipper",
  "REATTEMPT-OUTOFSTN": "Consignee not at delivery address",
} as const;

export const COMPLAINT_TOPICS = [
  { id: 1, label: "Billing Issue - Other", priority: "medium" },
  { id: 2, label: "Billing Issue - Weight Discrepancy", priority: "high" },
  { id: 3, label: "Change COD Amount", priority: "medium" },
  { id: 4, label: "Close the Account", priority: "low" },
  {
    id: 5,
    label: "COD - Parcel Delivered but not marked as Delivered by courier",
    priority: "high",
  },
  { id: 6, label: "COD - Remittance not received", priority: "high" },
  { id: 7, label: "Convert COD to Prepaid", priority: "medium" },
  { id: 8, label: "Convert Prepaid to COD", priority: "medium" },
  { id: 9, label: "Damage in Transit", priority: "high" },
  { id: 10, label: "DC Address Request", priority: "low" },
  { id: 11, label: "Delay in Delivery", priority: "high" },
  { id: 12, label: "Delay in Pickup", priority: "medium" },
  { id: 13, label: "Delay in Return", priority: "medium" },
  { id: 14, label: "Grievance", priority: "medium" },
  { id: 15, label: "Invoice", priority: "low" },
  { id: 16, label: "Other", priority: "low" },
  {
    id: 17,
    label: "Pickup Dispute - Parcel Picked but status is still Pending Pickup",
    priority: "high",
  },
  { id: 18, label: "Pincode Activation Delivery", priority: "medium" },
  { id: 19, label: "Pincode Activation - Pickup", priority: "medium" },
  { id: 20, label: "POD - Please provide Proof of Delivery", priority: "high" },
  { id: 21, label: "POD - Please provide Proof of Return", priority: "high" },
  {
    id: 22,
    label: "Product Mismatch - Incorrect Product Received",
    priority: "high",
  },
  { id: 23, label: "Re-Attempt Shipment Delivery", priority: "medium" },
  { id: 24, label: "Refund 30 days TAT Exceeded", priority: "medium" },
  { id: 25, label: "Refund - 45 days TAT Exceeded", priority: "medium" },
  { id: 26, label: "Refund - 60 days TAT Exceeded", priority: "high" },
  { id: 27, label: "Refund - Invalid POD", priority: "high" },
  { id: 28, label: "Refund - Lost Shipment", priority: "high" },
  { id: 29, label: "Refund Shipment Charges", priority: "medium" },
  { id: 30, label: "Shipment Creation Error", priority: "high" },
  { id: 31, label: "Shopify Tech Issue Suggestion", priority: "low" },
  { id: 32, label: "TDS Credit", priority: "medium" },
  { id: 33, label: "Technical", priority: "medium" },
  { id: 34, label: "Topup", priority: "medium" },
  {
    id: 35,
    label: "Untrackable in Ekart - Potentially Lost",
    priority: "high",
  },
  { id: 36, label: "Update Shipment - Change in Address", priority: "medium" },
  {
    id: 37,
    label: "Update Shipment - Change in Mobile number",
    priority: "medium",
  },
  {
    id: 38,
    label: "Update Shipment - Request RTO / Return",
    priority: "medium",
  },
  { id: 39, label: "Wallet Recharge / Topup Problem", priority: "high" },
  { id: 40, label: "Website Error", priority: "medium" },
  { id: 41, label: "Wordpress / Woocommerce Tech Issue", priority: "low" },
];
